-- The sequence of triangle numbers is generated by adding the natural numbers. So
-- the 7^(th) triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
-- ten terms would be:
-- 
-- 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
-- 
-- Let us list the factors of the first seven triangle numbers:
-- 
--  1: 1
--  3: 1,3
--  6: 1,2,3,6
-- 10: 1,2,5,10
-- 15: 1,3,5,15
-- 21: 1,3,7,21
-- 28: 1,2,4,7,14,28
-- 
-- We can see that 28 is the first triangle number to have over five divisors.
-- 
-- What is the value of the first triangle number to have over five hundred
-- divisors?
-- 
-- http://projecteuler.net/index.php?section=problems&id=12

module Main where

divisors :: Integral t => t -> [t]
divisors n = [m | m <- [1..(n `div` 2)], n `mod` m == 0] ++ [n]

main :: IO ()
main = do print $ head $ filter (\t -> (length . divisors) t > 500)
                       $ map (\n -> (n * (n + 1)) `div` 2) [1..]