/*
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */

var Fibonacci = (function ($) {
  var $ = function () {
    this.fibonaccis = [1, 1]
  }
  $.prototype = {
    get: function (n) {
      if(!this.fibonaccis[n]) {
        this.fibonaccis[n] = this.get(n - 1) + this.get(n - 2)
      }
      return this.fibonaccis[n]
    }
  }
  return new $()
})()

print(Fibonacci.get(10))
print(Fibonacci.get(100))
