/*
 * Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>

int main(int argc, char * argv[]) {
  long f1, f2, f3, sum;

  f1 = 0;
  f2 = 1;
  f3 = 0;
  sum = 0;

  while(f2 < 4000000) {
    f3 = f1 + f2;

    if((f2 & 1) == 0) {
      sum += f2;
    }

    f1 = f2;
    f2 = f3;
  }

  printf("%ld\n", sum);
  return 0;
}
